; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = "Beispielprojekt für die Verwendung von mehreren Boards in einem Projekt"
default_envs = nano, esp32, mega

[env]
framework = arduino
upload_port = /dev/ttyUSB*
monitor_speed = 115200

[env:nano]
platform = atmelavr
board = nanoatmega328
build_flags = -DENV_NANO=1

[env:esp32]
platform = espressif32
board = az-delivery-devkit-v4
build_flags = -DENV_ESP32=1

[env:mega]
platform = atmelavr
board = megaatmega2560
build_flags = -DENV_MEGA=1


